import React from "react";
import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <a href={`https://github.com/login/oauth/authorize?client_id=78f8b7a64f149e72ca42`}>Authenticate</a>
        </div>
      </main>
    </React.Fragment>
  );
};

export default Home;
